url: http://www.seohzz.com

title: 个人介绍

keywords: 陈智毅

description: 陈智毅是广州医学院第三附属医院超声医学科主任，美国Drexel University访问学者，华中科技大学兼职硕士生导师。

relative_permalinks: false

contacts: 陈生

tel: 13890019668



exclude:
  - README.md
